export const seedInstitutions = [
  { id:'INST-BUX-0001', name:'Buxoro viloyat bolalar ko‘p tarmoqli tibbiyot markazi', district:'Buxoro shahri' },
  { id:'INST-BUX-0002', name:'Buxoro viloyat ko‘p tarmoqli tibbiyot markazi', district:'Buxoro shahri' },
  { id:'INST-BUX-0003', name:'Buxoro shahar tug‘ruq kompleksi', district:'Buxoro shahri' },
  { id:'INST-BUX-0004', name:'Respublika shoshilinch tibbiy yordam ilmiy markazi Buxoro filiali', district:'Buxoro shahri' },
  { id:'INST-BUX-0005', name:'Respublika ixtisoslashtirilgan onkologiya va radiologiya markazi Buxoro filiali', district:'Buxoro shahri' },
  { id:'INST-BUX-0006', name:'Buxoro viloyat tibbiy diagnostika markazi', district:'Buxoro shahri' },
  { id:'INST-BUX-0007', name:'Buxoro viloyat OITSga qarshi kurashish markazi', district:'Buxoro shahri' },
  { id:'INST-BUX-0008', name:'Buxoro viloyat qon quyish stansiyasi', district:'Buxoro shahri' },
  { id:'INST-BUX-0009', name:'Respublika ixtisoslashtirilgan ona va bola salomatligi ilmiy-amaliy tibbiyot markazi Buxoro filiali', district:'Buxoro shahri' },
  { id:'INST-BUX-0010', name:'Respublika ixtisoslashtirilgan ruhiy salomatlik ilmiy-amaliy tibbiyot markazi Buxoro filiali', district:'Buxoro shahri' },
  { id:'INST-BUX-0011', name:'Buxoro davlat tibbiyot instituti klinikasi', district:'Buxoro shahri' },
  { id:'INST-BUX-0012', name:'Buxoro viloyat endokrinologiya dispanseri', district:'Buxoro shahri' },
  { id:'INST-BUX-0013', name:'Buxoro viloyat yuqumli kasalliklar shifoxonasi', district:'Buxoro shahri' },
  { id:'INST-BUX-0014', name:'Buxoro viloyat ftiziatriya va pulmonologiya markazi', district:'Buxoro shahri' },
  { id:'INST-BUX-0015', name:'Buxoro shahar tibbiyot birlashmasi', district:'Buxoro shahri' },
  { id:'INST-BUX-0016', name:'Kogon shahar tibbiyot birlashmasi', district:'Kogon shahri' },
  { id:'INST-BUX-0017', name:'Kogon tuman tibbiyot birlashmasi', district:'Kogon tumani' },
  { id:'INST-BUX-0018', name:'Jondor tuman tibbiyot birlashmasi', district:'Jondor tumani' },
  { id:'INST-BUX-0019', name:'Shofirkon tuman tibbiyot birlashmasi', district:'Shofirkon tumani' },
  { id:'INST-BUX-0020', name:'Qorako‘l tuman tibbiyot birlashmasi', district:'Qorako‘l tumani' },
  { id:'INST-BUX-0021', name:'Qorovulbozor tuman tibbiyot birlashmasi', district:'Qorovulbozor tumani' },
  { id:'INST-BUX-0022', name:'Romitan tuman tibbiyot birlashmasi', district:'Romitan tumani' },
  { id:'INST-BUX-0023', name:'Peshku tuman tibbiyot birlashmasi', district:'Peshku tumani' },
  { id:'INST-BUX-0024', name:'G‘ijduvon tuman tibbiyot birlashmasi', district:'G‘ijduvon tumani' }
];
