ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS is_complaint INTEGER NOT NULL DEFAULT 0;
ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS citizen_name TEXT NOT NULL DEFAULT '';
ALTER TABLE feedbacks ADD COLUMN IF NOT EXISTS citizen_phone TEXT NOT NULL DEFAULT '';
